server:
  port: 8087

spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead_authuser
    username: postgres
    password: test
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
