#server:
#  port: 8082
#  servlet:
#    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        service-id: config-server


#  datasource:
#    url:  jdbc:postgresql://localhost:5432/ead_course
#    username: postgres
#    password: test
#  jpa:
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      jdbc:
#        lob.non-contextual-creation: true
#    properties:
#      hibernate:
#        show_sql: true
#  output:
#    ansi:
#      enabled: Always
#  rabbitmq:
#    addresses: amqps://zzzvezfi:cKqzep4O3t_gP7hp4ksbzGifxlAA0IQl@moose.rmq.cloudamqp.com/zzzvezfi
#
#
#ead:
#  api:
#    url:
#      authuser: 'http://ead-authuser-service'
#  broker:
#    exchange:
#      userEventExchange: ead.userevent
#    queue:
#      userEventQueue:
#        name: ead.userevent.ms.course
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    instance:
#      hostname: localhost
