server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead_course
    username: postgres
    password: test
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
    address: amqps://ikyduabx:bgivZPF1L09hbe6QyxNnvqTsOGN3gqv2@fish.rmq.cloudamqp.com/ikyduabx


ead:
  api:
    url:
      authuser: 'http://ead-authuser-service'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
